name: tflite_audio_detection
description: Easy, fast processing and manipulation input and output of TensorFlow Lite Models.
version: 1.0.0
homepage: https://github.com/ductung-bfast/tflite_flutter_helper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  quiver: ^3.0.1
  ffi: ^2.0.2
  path_provider: ^2.0.1
  tflite_flutter: ^0.10.1
dev_dependencies:
  flutter_test:
    sdk: flutter
